### ISSUE TITLE
Planificación del Proyecto

### ISSUE THREAD

**Issue by fps1001** [fps1001/GESPRO_GESTIONTAREAS#1]

**Comment by fps1001** [comment]
Empezamos con el Proyecto.

**Comment by far0010** [comment]
Ok, de acuerdo. Tenemos que efectuar la planificación.
Qué puntos vamos a tratar?

**Comment by far0010** [comment]
Creo que debería hablar con el ayto. para que me faciliten acceso al gps de los autobuses, no?

**Comment by fps1001** [comment]
De acuerdo. Creo una nueva tarea y me la asigno.
He solicitado una reunión con el técnico del Ayuntamiento.

**Comment by far0010** [comment]
ok, yo iré hablando con responsables de la Universidad para que nos faciliten acceso a su aplicación.

**Comment by fps1001** [comment]
Se revisa la planificación y se resuelve que está completa.

**Comment by far0010** [comment]
Ok, si está correcta vamos cerrando esta fase y avanzamos.

**Comment by fps1001** [comment]
Estamos de acuerdo. Se da por cerrada. Buen trabajo. Gracias @far0010
